### PR TITLE
Infinite Loop When Channels Leak

### LINKED ISSUE #295: Infinite Loop When Channels Leak
### Expected Behavior

If a connection can't be created in the connection pool, an exception should be thrown

It looks like here there is just an infinite loop here: https://github.com/micronaut-projects/micronaut-rabbitmq/blob/master/rabbitmq/src/main/java/io/micronaut/rabbitmq/connect/DefaultChannelPool.java#L79

Where on line 84 if that returns null, we just try again infinitely but createChannel() can fail if no one has removed anything from it. Not sure how easy it is to change that behaviour, maybe logging a warning after 1 minute is enough, that code does busy wait, so if you do have a legitimate need use for running out of channels, then that is probably not an efficient algorithm.

### Actual Behaviour

High CPU usage

### Steps To Reproduce

Run something like the following code:

```
while(true) { 
                channelPool.getChannel().basicPublish("some-exchange", "some-routing-key", null, "Test".getBytes(StandardCharsets.UTF_8);
                }
```

### Environment Information

Linux
Java 14

### Example Application

_No response_

### Version

2.5.0

### PR DESCRIPTION
**Pull request by guillermocalvo**
Closes #295 

@sdelamo 
Instead of throwing an exception as the issue suggests, the connection pool will return `null`.

[`getChannel`](https://github.com/micronaut-projects/micronaut-rabbitmq/blob/master/rabbitmq/src/main/java/io/micronaut/rabbitmq/connect/ChannelPool.java#L46) makes no promises about nullability, so I think this should be safe.

Please let me know if you rather throw an `IOException`.

### CODE REVIEW

File: rabbitmq/src/main/java/io/micronaut/rabbitmq/connect/DefaultChannelPool.java [hunk 1]
```diff
@@ -82,6 +82,13 @@ public Channel getChannel() throws IOException {
             channel = channels.poll();
             if (channel == null) {
                 channel = createChannel();
+                // Check that the channel was actually created to avoid infinite loop
```
Comment (sdelamo) [inline rabbitmq/src/main/java/io/micronaut/rabbitmq/connect/DefaultChannelPool.java:85]: Based on the Javadoc of `ChannelPool::getChannel` an `IOException` is more correct. 

> If a channel needed to be created and encountered an error

**Review by sdelamo — CHANGES_REQUESTED** [review]
