### PR TITLE
Send application events before/after RabbitMQ consumer subscribe to a queue

### LINKED ISSUE #423: Listeners start consuming messages before Micronaut Startup Event
### Issue Details

We have a bunch of external dependencies that we configure using the startup event.

```kotlin
/* Bootstrap.kt */

@EventListener
fun onStartupEvent(@Suppress("UNUSED_PARAMETER") event: ServerStartupEvent) {
    // Add all bootstrap services here
    configureOpenSearch()
    configureSentry()
}
```

We're working on integrating the `micronaut-rabbitmq` library for task queues and the first consumer that we have written uses OpenSearch client to fetch some data for further processing. We published some messages using the management console and started the framework. To our surprise, the consumer code started executing early before the bootstrap code had a chance to execute and as a result it can't connect to Opensearch.

I'm not sure if this is by design but the expected behavior for the consumers is to wait for loading the framework completely before consuming any messages.

### Steps To Reproduce

You should be able to reproduce this issue by putting log statements in the bootstrap file and consumer code and verifying their order of execution.

Right now, we're working around this issue by making a new connection to OpenSearch in the consumer thread.

### Environment Information

- Operating System: Linux (Ubuntu 20.4)
- JDK: GraalVM 22 (Java 17)

### Example Application

_No response_

### Version

3.4

### PR DESCRIPTION
**Pull request by guillermocalvo**
Closes #423 

Instead of delaying message consumption, we will emit application events so that users can take any necessary actions before/after RabbitMQ consumers subscribe to a queue.

### CODE REVIEW

File: docs-examples/example-groovy/src/test/groovy/io/micronaut/rabbitmq/docs/event/MyStartingEventListener.groovy [hunk 1]
```diff
@@ -0,0 +1,19 @@
...
+import jakarta.inject.Singleton
+// end::imports[]
+
+@Requires(property = "spec.name", value = "RabbitListenerEventsSpec")
+// tag::clazz[]
+@Singleton
+class MyStartingEventListener implements ApplicationEventListener<RabbitConsumerStarting> {
+  @Override
+  void onApplicationEvent(RabbitConsumerStarting event) {
+    System.out.println("RabbitMQ consumer: ${event.source} (method: ${event.method}) is subscribing to: ${event.queue}")
```
Comment (sdelamo) [inline docs-examples/example-groovy/src/test/groovy/io/micronaut/rabbitmq/docs/event/MyStartingEventListener.groovy:16]: use `LOG` instead of `println`

`private static final Logger LOG = LoggerFactory.getLogger(MyStartingEventListener.class);`

File: docs-examples/example-java/src/test/java/io/micronaut/rabbitmq/docs/event/MyStartedEventListener.java [hunk 2]
```diff
@@ -0,0 +1,22 @@
...
+import jakarta.inject.Singleton;
+// end::imports[]
+
+@Requires(property = "spec.name", value = "RabbitListenerEventsSpec")
+// tag::clazz[]
+@Singleton
+public class MyStartedEventListener implements ApplicationEventListener<RabbitConsumerStarted> {
+  @Override
+  public void onApplicationEvent(RabbitConsumerStarted event) {
+    System.out.println(new StringBuilder()
```
Comment (sdelamo) [inline docs-examples/example-java/src/test/java/io/micronaut/rabbitmq/docs/event/MyStartedEventListener.java:16]: use `LOG` instead of `println`

`private static final Logger LOG = LoggerFactory.getLogger(MyStartingEventListener.class);`

File: docs-examples/example-java/src/test/java/io/micronaut/rabbitmq/docs/event/MyStartingEventListener.java [hunk 3]
```diff
@@ -0,0 +1,22 @@
...
+import jakarta.inject.Singleton;
+// end::imports[]
+
+@Requires(property = "spec.name", value = "RabbitListenerEventsSpec")
+// tag::clazz[]
+@Singleton
+public class MyStartingEventListener implements ApplicationEventListener<RabbitConsumerStarting> {
+  @Override
+  public void onApplicationEvent(RabbitConsumerStarting event) {
+    System.out.println(new StringBuilder()
```
Comment (sdelamo) [inline docs-examples/example-java/src/test/java/io/micronaut/rabbitmq/docs/event/MyStartingEventListener.java:16]: use `LOG` instead of `println`

`private static final Logger LOG = LoggerFactory.getLogger(MyStartingEventListener.class);`

File: docs-examples/example-kotlin/src/test/kotlin/io/micronaut/rabbitmq/docs/event/MyStartedEventListener.kt [hunk 4]
```diff
@@ -0,0 +1,18 @@
...
+import io.micronaut.rabbitmq.event.RabbitConsumerStarted
+import jakarta.inject.Singleton
+// end::imports[]
+
+@Requires(property = "spec.name", value = "RabbitListenerEventsSpec")
+// tag::clazz[]
+@Singleton
+class MyStartedEventListener : ApplicationEventListener<RabbitConsumerStarted> {
+  override fun onApplicationEvent(event: RabbitConsumerStarted) {
+    println("RabbitMQ consumer: ${event.source} (method: ${event.method}) just subscribed to: ${event.queue}")
```
Comment (sdelamo) [inline docs-examples/example-kotlin/src/test/kotlin/io/micronaut/rabbitmq/docs/event/MyStartedEventListener.kt:15]: use `LOG` instead of `println`

`private static final Logger LOG = LoggerFactory.getLogger(MyStartingEventListener.class);`

File: docs-examples/example-kotlin/src/test/kotlin/io/micronaut/rabbitmq/docs/event/MyStartingEventListener.kt [hunk 5]
```diff
@@ -0,0 +1,18 @@
...
+import io.micronaut.rabbitmq.event.RabbitConsumerStarting
+import jakarta.inject.Singleton
+// end::imports[]
+
+@Requires(property = "spec.name", value = "RabbitListenerEventsSpec")
+// tag::clazz[]
+@Singleton
+class MyStartingEventListener : ApplicationEventListener<RabbitConsumerStarting> {
+  override fun onApplicationEvent(event: RabbitConsumerStarting) {
+    println("RabbitMQ consumer: ${event.source} (method: ${event.method}) is subscribing to: ${event.queue}")
```
Comment (sdelamo) [inline docs-examples/example-kotlin/src/test/kotlin/io/micronaut/rabbitmq/docs/event/MyStartingEventListener.kt:15]: use `LOG` instead of `println`

`private static final Logger LOG = LoggerFactory.getLogger(MyStartingEventListener.class);`

**Review by sdelamo — CHANGES_REQUESTED** [review]

**Comment by sdelamo** [comment]
@aniljaiswal Will this proposed solution help your use case?

File: rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java [hunk 6]
```diff
@@ -101,6 +102,7 @@ public class RabbitMQConsumerAdvice implements ExecutableMethodProcessor<Queue>,
      * @param serDesRegistry    The serialization/deserialization registry
      * @param conversionService The service to convert consume argument values
      * @param channelPools      The channel pools to retrieve channels
+     * @since 4.1.0
      */
     public RabbitMQConsumerAdvice(BeanContext beanContext,
```
Comment (sdelamo) [inline rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java:107]: annotate the new constructor with `@Inject`

**Review by sdelamo — CHANGES_REQUESTED** [review]

File: rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java [hunk 7]
```diff
@@ -112,6 +127,37 @@ public RabbitMQConsumerAdvice(BeanContext beanContext,
...
+    /**
+     * Deprecated constructor.
+     *
+     * @param beanContext       The bean context
+     * @param binderRegistry    The registry to bind arguments to the method
+     * @param exceptionHandler  The exception handler to use if the consumer isn't a handler
+     * @param serDesRegistry    The serialization/deserialization registry
+     * @param conversionService The service to convert consume argument values
+     * @param channelPools      The channel pools to retrieve channels
+     * @deprecated
```
Comment (sdelamo) [inline rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java:139]: tell users in the `@deprecated` java doc to use the other constructor instead with `{@link`

**Review by sdelamo — CHANGES_REQUESTED** [review]

File: rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java (hunk 7 above)
Comment (guillermocalvo) [inline rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java:139]:
```suggestion
     * @deprecated Use @{link {@link RabbitMQConsumerAdvice#RabbitMQConsumerAdvice(BeanContext, ApplicationEventPublisher, ApplicationEventPublisher, RabbitBinderRegistry, RabbitListenerExceptionHandler, RabbitMessageSerDesRegistry, ConversionService, List)}}
```

File: rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java [hunk 8]
```diff
@@ -112,6 +127,37 @@ public RabbitMQConsumerAdvice(BeanContext beanContext,
...
+    @Deprecated(since = "4.1.0", forRemoval = true)
+    public RabbitMQConsumerAdvice(BeanContext beanContext,
+        RabbitBinderRegistry binderRegistry,
+        RabbitListenerExceptionHandler exceptionHandler,
+        RabbitMessageSerDesRegistry serDesRegistry,
+        ConversionService conversionService,
+        List<ChannelPool> channelPools) {
+        this(
+            beanContext,
+            beanContext.findBean(Argument.of((Class<ApplicationEventPublisher<RabbitConsumerStarting>>) ((Class) ApplicationEventPublisher.class),
```
Comment (sdelamo) [inline rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java:150]:
```suggestion
            beanContext.getBean(Argument.of(ApplicationEventPublisher.class, RabbitConsumerStarting.class)),
```

File: rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java [hunk 9]
```diff
@@ -112,6 +127,37 @@ public RabbitMQConsumerAdvice(BeanContext beanContext,
...
+                Argument.of(RabbitConsumerStarting.class))).orElseThrow(),
```
Comment (sdelamo) [inline rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java:151]:
```suggestion
```

File: rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java [hunk 10]
```diff
@@ -112,6 +127,37 @@ public RabbitMQConsumerAdvice(BeanContext beanContext,
...
+            beanContext.findBean(Argument.of((Class<ApplicationEventPublisher<RabbitConsumerStarted>>) ((Class) ApplicationEventPublisher.class),
```
Comment (sdelamo) [inline rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java:152]:
```suggestion
            beanContext.getBean(Argument.of(ApplicationEventPublisher.class, RabbitConsumerStarted.class)),
```

File: rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java [hunk 11]
```diff
@@ -112,6 +127,37 @@ public RabbitMQConsumerAdvice(BeanContext beanContext,
...
+                Argument.of(RabbitConsumerStarted.class))).orElseThrow(),
```
Comment (sdelamo) [inline rabbitmq/src/main/java/io/micronaut/rabbitmq/intercept/RabbitMQConsumerAdvice.java:153]:
```suggestion
```

**Review by sdelamo — CHANGES_REQUESTED** [review]
